### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by maxxporoshin** [festinuz/playing_with_python#4]
D:\Coding\playing_with_python\yandex>py __main__.py -d 0 -f _2
Traceback (most recent call last):
  File "__main__.py", line 52, in <module>
    print(out)
  File "C:\Program Files (x86)\Python 3.5\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-8: character maps to <undefined>

**Comment by festinuz** [comment]
It's because, apparently, your windows console does not support utf-8. I frankly don't know why it is the case, since on my windows system it works like a charm.

In short, try looking up on how to add unicode to your cmd.exe.
